name: Build jobs

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    container: ghcr.io/pgalonza/devkita64-atmosphere:d5891f6bd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Atmosphere
        shell: bash
        run: |
          source /opt/venv/bin/activate
          git config --global --add safe.directory "*"
          python3 ./stratosphere/loader/source/patch.py
          make -f atmosphere.mk dist-no-debug
          hactool -t kip1 ./stratosphere/loader/out/nintendo_nx_arm64_armv8a/release/loader.kip \
          --uncompress=./stratosphere/loader/out/nintendo_nx_arm64_armv8a/release/loader-uncompress.kip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: atmosphere-artifacts
          path: |
            ./out/nintendo_nx_arm64_armv8a/release/*
            ./stratosphere/loader/out/nintendo_nx_arm64_armv8a/release/*
